INSERT INTO "niches" ("name") VALUES ('Artes');
INSERT INTO "niches" ("name") VALUES ('Artigos de Luxo');
INSERT INTO "niches" ("name") VALUES ('Ativismo & Causas Sociais');
INSERT INTO "niches" ("name") VALUES ('Beleza & Maquiagem');
INSERT INTO "niches" ("name") VALUES ('Brinquedos');
INSERT INTO "niches" ("name") VALUES ('Carros, Motocicletas & Veículos');
INSERT INTO "niches" ("name") VALUES ('Casamento');
INSERT INTO "niches" ("name") VALUES ('Ciências & Curiosidades');
INSERT INTO "niches" ("name") VALUES ('Churrasco');
INSERT INTO "niches" ("name") VALUES ('Construção Civil');
INSERT INTO "niches" ("name") VALUES ('Crianças & Bebês');
INSERT INTO "niches" ("name") VALUES ('Cultura Nerd');
INSERT INTO "niches" ("name") VALUES ('Decoração');
INSERT INTO "niches" ("name") VALUES ('Diversidade & Empoderamento');
INSERT INTO "niches" ("name") VALUES ('Educação');
INSERT INTO "niches" ("name") VALUES ('Esportes');
INSERT INTO "niches" ("name") VALUES ('Faça Você Mesmo');
INSERT INTO "niches" ("name") VALUES ('Família & Maternidade');
INSERT INTO "niches" ("name") VALUES ('Fitness');
INSERT INTO "niches" ("name") VALUES ('Finanças');
INSERT INTO "niches" ("name") VALUES ('Games');
INSERT INTO "niches" ("name") VALUES ('Gastronomia, Comidas, Bebidas & Receitas');
INSERT INTO "niches" ("name") VALUES ('Humor');
INSERT INTO "niches" ("name") VALUES ('Lifestyle');
INSERT INTO "niches" ("name") VALUES ('Livros & Leitura');
INSERT INTO "niches" ("name") VALUES ('Moda');
INSERT INTO "niches" ("name") VALUES ('Música');
INSERT INTO "niches" ("name") VALUES ('Negócios & Empreendedorismo');
INSERT INTO "niches" ("name") VALUES ('Opinião');
INSERT INTO "niches" ("name") VALUES ('Pets, Animais, Biologia');
INSERT INTO "niches" ("name") VALUES ('Saúde');
INSERT INTO "niches" ("name") VALUES ('Tecnologia');
INSERT INTO "niches" ("name") VALUES ('Varejo');
INSERT INTO "niches" ("name") VALUES ('Variedades');
INSERT INTO "niches" ("name") VALUES ('Viagens');
INSERT INTO "niches" ("name") VALUES ('Política');
INSERT INTO "niches" ("name") VALUES ('Tv, Séries, Filmes, Cinema');
INSERT INTO "niches" ("name") VALUES ('Direito, Advocacia');
INSERT INTO "niches" ("name") VALUES ('Fotografia');
INSERT INTO "niches" ("name") VALUES ('Agricultura, Rural');
INSERT INTO "niches" ("name") VALUES ('Dança');
INSERT INTO "niches" ("name") VALUES ('Notícias & Atualidades');
