name: InfluenceHub CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test || echo "::set-output name=tests_failed::true"
    - run: npx eslint .

  check-status:
      runs-on: ubuntu-latest
      needs: build
      if: ${{ always() }}

      steps:
      - name: Check if all tests passed
      - run: exit ${{ steps.build.outputs.tests_failed == 'true' }}
      - id: check_status
